# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0015_auto_20180304_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
