# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0016_auto_20180611_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
